const dummyPosts = [
  {
    _id: "1",
    title: "Mastering React in 2025",
    desc: "React continues to dominate the frontend landscape. Learn what's new and how to use it effectively.",
    photo: "https://picsum.photos/seed/react/800/600",
    createdAt: "2025-04-25T10:00:00Z",
    categories: ["Tech", "React"],
  },
  {
    _id: "2",
    title: "10 Tips for Better Sleep",
    desc: "A good night’s sleep boosts your productivity and health. Here's how to improve yours.",
    photo: "https://source.unsplash.com/800x600/?sleep,bed",
    createdAt: "2025-04-22T12:30:00Z",
    categories: ["Health"],
  },
  {
    _id: "3",
    title: "Why You Should Start Journaling",
    desc: "Journaling can increase clarity and focus. Here’s how to make it a habit.",
    photo: "https://source.unsplash.com/800x600/?journal,writing",
    createdAt: "2025-04-20T09:15:00Z",
    categories: ["Self Improvement"],
  },
  {
    _id: "4",
    title: "AI Trends Shaping 2025",
    desc: "Explore the latest in artificial intelligence and how it's changing our world.",
    photo: "https://source.unsplash.com/800x600/?ai,artificial-intelligence",
    createdAt: "2025-04-18T15:00:00Z",
    categories: ["Tech", "AI"],
  },
  {
    _id: "5",
    title: "How to Stay Focused While Working Remote",
    desc: "Work-from-home distractions are real. Here’s how to stay on track.",
    photo: "https://source.unsplash.com/800x600/?remote-work,laptop",
    createdAt: "2025-04-15T08:20:00Z",
    categories: ["Productivity"],
  },
  {
    _id: "6",
    title: "Top 5 JavaScript Tricks You Didn’t Know",
    desc: "Discover handy JavaScript features that can make your code cleaner and more efficient.",
    photo: "https://source.unsplash.com/800x600/?javascript,code",
    createdAt: "2025-04-13T17:45:00Z",
    categories: ["Tech", "JavaScript"],
  },
  {
    _id: "7",
    title: "The Power of Daily Walks",
    desc: "Walking daily is simple, yet powerful. Let’s explore its benefits.",
    photo: "https://source.unsplash.com/800x600/?walking,park",
    createdAt: "2025-04-11T14:30:00Z",
    categories: ["Health", "Self Improvement"],
  },
  {
    _id: "8",
    title: "Understanding Web 3.0",
    desc: "What is Web 3.0 and how is it different from Web 2.0? Let’s break it down.",
    photo: "https://source.unsplash.com/800x600/?web3,blockchain",
    createdAt: "2025-04-09T19:00:00Z",
    categories: ["Tech"],
  },
  {
    _id: "9",
    title: "Declutter Your Mind in 5 Minutes a Day",
    desc: "Simple exercises to clear your mind and reset your focus.",
    photo: "https://source.unsplash.com/800x600/?meditation,calm",
    createdAt: "2025-04-07T07:00:00Z",
    categories: ["Self Improvement"],
  },
  {
    _id: "10",
    title: "Beginner’s Guide to Investing",
    desc: "Learn how to start investing with minimal risk.",
    photo: "https://source.unsplash.com/800x600/?finance,investing",
    createdAt: "2025-04-05T11:15:00Z",
    categories: ["Finance"],
  },
  {
    _id: "11",
    title: "Understanding Climate Change",
    desc: "The basics of climate change and why it matters more than ever.",
    photo: "https://source.unsplash.com/800x600/?climate-change,environment",
    createdAt: "2025-04-03T13:45:00Z",
    categories: ["Current Affairs"],
  },
  {
    _id: "12",
    title: "Digital Minimalism in a Hyper-Connected World",
    desc: "Cutting down on digital noise can change your life. Here's how.",
    photo: "https://source.unsplash.com/800x600/?minimalism,clean",
    createdAt: "2025-04-01T10:00:00Z",
    categories: ["Self Improvement"],
  },
  {
    _id: "13",
    title: "Freelancing in 2025: What You Need to Know",
    desc: "The freelancing landscape is evolving. Stay ahead with these tips.",
    photo: "https://source.unsplash.com/800x600/?freelance,workspace",
    createdAt: "2025-03-30T16:30:00Z",
    categories: ["Business", "Tech"],
  },
  {
    _id: "14",
    title: "How to Cook Simple Healthy Meals",
    desc: "Easy and healthy meal ideas for busy people.",
    photo: "https://source.unsplash.com/800x600/?cooking,healthy-food",
    createdAt: "2025-03-28T18:00:00Z",
    categories: ["Health", "Lifestyle"],
  },
  {
    _id: "15",
    title: "Time Management for Creatives",
    desc: "Struggling with structure? These time management hacks are for you.",
    photo: "https://source.unsplash.com/800x600/?time-management,calendar",
    createdAt: "2025-03-26T20:10:00Z",
    categories: ["Productivity"],
  },
  {
    _id: "16",
    title: "Reading More Books in Less Time",
    desc: "Speed reading tips and strategies to retain more and read faster.",
    photo: "https://source.unsplash.com/800x600/?books,reading",
    createdAt: "2025-03-24T09:00:00Z",
    categories: ["Education"],
  },
  {
    _id: "17",
    title: "What’s New in CSS in 2025",
    desc: "CSS is getting powerful. Here are the newest features you should know.",
    photo: "https://source.unsplash.com/800x600/?css,web-design",
    createdAt: "2025-03-22T07:45:00Z",
    categories: ["Tech", "CSS"],
  },
  {
    _id: "18",
    title: "The Rise of Remote Education",
    desc: "How online learning is transforming traditional education models.",
    photo: "https://source.unsplash.com/800x600/?education,learning",
    createdAt: "2025-03-20T12:00:00Z",
    categories: ["Education"],
  },
  {
    _id: "19",
    title: "Breaking News: Market Hits Record High",
    desc: "Stocks soar as global markets react to tech boom.",
    photo: "https://source.unsplash.com/800x600/?stock-market,finance",
    createdAt: "2025-03-18T14:00:00Z",
    categories: ["Current Affairs", "Finance"],
  },
  {
    _id: "20",
    title: "The Science Behind Gratitude",
    desc: "Gratitude isn't just a feeling—it rewires your brain for positivity.",
    photo: "https://source.unsplash.com/800x600/?gratitude,happiness",
    createdAt: "2025-03-16T10:00:00Z",
    categories: ["Self Improvement", "Health"],
  },
];

export default dummyPosts;
